### ISSUE TITLE
Font Bakery Result mismatching numbers

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/fontbakery-dashboard#122]
The Font Bakery Result shows different numbers between the summary and the details on the report (once clicking for details). These numbers are also different from the ones resulted on last QA run by command line.

[Alata](https://fontbakery.graphicore.de/report/3c207533-c836-49c9-8e11-35ef8a9ae9aa) process
Last [QA5](https://github.com/vv-monsalve/Alata/blob/QA-Alata/fonts/qaAlata5/Fontbakery/report.md) run from the command line

### **Summary:**
![Screen Shot 2019-09-04 at 13 51 30](https://user-images.githubusercontent.com/48698976/64290831-78943400-cf2c-11e9-87cb-93c4f2ffc492.png)
 

---- 

### **Clicking to see details:**

![Screen Shot 2019-09-04 at 13 51 55](https://user-images.githubusercontent.com/48698976/64290843-7e8a1500-cf2c-11e9-9bab-11aa65f06796.png)

------

### **Command line**
![Screen Shot 2019-09-04 at 16 54 55](https://user-images.githubusercontent.com/48698976/64294589-cf057080-cf34-11e9-80b7-5f6df183f0b1.png)

**Comment by vv-monsalve** [comment]
Checking it again, I realize now that the Fail reported is on "Family" regarding the Designer information, which was solved by adding it on the Dashboard Spreadsheet. 
But, there is also a Warn about ftxvalidator is not available. [FB report](https://fontbakery.graphicore.de/report/dcc62d53-c2a7-40c0-bc82-322494776252)

**Comment by graphicore** [comment]
Thanks for reporting.

The results between the summary and the detailed report are the same, but your screenshot only shows the results for just the file, not the "Family Checks".

`ftxvalidator` is indeed not available, because we don't have access to Mac OSX servers, that's well known.

The "Designer" field, if not in the spreadsheet, should come from the METADATA.pb in [github google/fonts master](https://github.com/google/fonts/tree/master/ofl/alata) but the family is not there yet. In general it is very good when the info is in the spreadsheet, as we create a single source of truth for this kind of information.

Not sure about the different number of results between your CLI and the online version, could be many things.
