### ISSUE TITLE
Dispatcher UI: Finish Process option for FB task

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/fontbakery-dashboard#135]
The UI for Fontbakery task could follow the structure of _Diffenator_, and _BrowsersDiffsAndPreviews_ to communicate better what to do when FB is not ok.
Which is: having the question "How to proceed" as a headline, a checkbox to Finish the process and after that, the checkbox option to indicate if everything is good or no, would be more intuitive.

**Comment by graphicore** [comment]
The Font Bakery task is different from the Deffenator and Browser Diffs tasks, because after the report was generated it can only be finished, the other tasks have options to compare with other versions/sources of the family and can hence be re-run.

I'm trying a new version of the from regardless, in the hope to be better understood.


OLD:

![Screenshot from 2019-10-22 03-28-27](https://user-images.githubusercontent.com/393132/67255896-c0dbc700-f484-11e9-9b06-51d62873b8ab.png)

![Screenshot from 2019-10-22 03-29-15](https://user-images.githubusercontent.com/393132/67255899-c3d6b780-f484-11e9-9703-806b77adda91.png)

NEW:

![Screenshot from 2019-10-22 04-12-05](https://user-images.githubusercontent.com/393132/67255912-cf29e300-f484-11e9-96e4-4974f855cd31.png)

![Screenshot from 2019-10-22 04-12-34](https://user-images.githubusercontent.com/393132/67255923-da7d0e80-f484-11e9-9cfc-c2abab255c70.png)


---
Diffing interfaces like this:

![Screenshot from 2019-10-22 03-29-40](https://user-images.githubusercontent.com/393132/67255980-12845180-f485-11e9-8368-0e51743b10b1.png)


![Screenshot from 2019-10-22 03-30-31](https://user-images.githubusercontent.com/393132/67255987-1adc8c80-f485-11e9-88be-736d493e0571.png)

Though I reworded from "Finish this process." to "Finish this task." as that was an error:

![Screenshot from 2019-10-22 04-13-08](https://user-images.githubusercontent.com/393132/67256005-32b41080-f485-11e9-9fbf-b8065fbfc5af.png)
