### ISSUE TITLE
An option to dismiss or end without fail the Diffenator task

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/fontbakery-dashboard#140]
When working with a Font that is new on GF (e.g. this case Gupter) a third option to finish Diffenator task besides Ok or Fail is needed to prevent the PR from stuck.

When ending the process by leaving the "it is ok" checkbox uncheck and with a Note: ("Because the font is new on GF") the task remained as Fail and this seemed to somehow block the PR.
https://fontbakery.graphicore.de/dispatcher/process/30cbaadd-3ffd-4536-8168-a7a22073ffd8

On the other hand, the process seemed to work well when it was marked as "Task ApproveProcess OK @vv-monsalve confirms the family package"
https://github.com/graphicore/googleFonts/pull/39

**Comment by graphicore** [comment]
Technically checking OK because it's not needed to look at that report (e.g. because it's a new family) or because it passes is the same.

However, I changed the UI of the Diffenator tasks to add an explicit SKIP option. It's also noted in the report history which option was chosen, otherwise it's the same result as choosing OK.

NEW:

![Screenshot from 2019-10-22 05-11-33](https://user-images.githubusercontent.com/393132/67257346-d43e6080-f48b-11e9-9245-ff64da865b62.png)

OLD:

![Screenshot from 2019-10-22 03-30-31](https://user-images.githubusercontent.com/393132/67257359-df918c00-f48b-11e9-871d-63d0621cc275.png)
