### ISSUE TITLE
Inform users what will happen when they drop

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery-dashboard#67]
## Observed behaviour

Users want to know (a) if anything is uploaded and (b) what the Terms of Service and Privacy Policy are.

## Expected behaviour

https://github.com/googlefonts/fontbakery-dashboard/blob/012c415461755c88b9c927508046c7f10e62d402/containers/base/javascript/browser/html/client.html explains these things

**Comment by graphicore** [comment]
Just added this description to the drag and drop client:

<h3>What happens with my files?</h3>
<p>
Your files will be uploaded to our servers. We keep them around until Font Bakery finished running
the checks and creating its report. After checking, your files are removed from our servers.
</p><p>
The Font Bakery report created for your files, however, remains in our database, so that you can
share and revisit the link to the report. <strong>Everyone with the link can view a report.</strong>
The link contains the random unique ID of the report, created by the database server, it should be
really hard to guess. We do not keep outline data or actual font files, but, the report can contain
some detailed information about your fonts, like file names, name table entries and generally problems
found in your fonts and metadata etc.
</p>
<p>For further questions, discussion and bug reports please see our
<a href="https://github.com/googlefonts/fontbakery-dashboard/issues">GitHub issue tracker</a>.</p>
